### ISSUE TITLE
PA Review: Restaurant Search

### ISSUE THREAD

**Issue by dmccapes4** [dmccapes4/eat_time#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by anastassia-b** [comment]
- [ ] Give the `input#restaurant.restaurant-input` some placeholder text or a small magnifying glass icon so the user knows they can enter anything there.

**Comment by anastassia-b** [comment]
Great, the search works on different parameters (Cuisine, Location, and Restaurant name) and returns the results. The core functionality is complete.

After you complete the other MVPs, consider revamping your search feature to:
- [ ] Use regex to search on restaurant name.
- [ ] Write custom reservation filter method.

This MVP is complete.
