### ISSUE TITLE
PA Review: Restaurant Index and Show

### ISSUE THREAD

**Issue by dmccapes4** [dmccapes4/eat_time#8]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by anastassia-b** [comment]
This is really good progress, great seed data. A few comments:

- [ ] The body-img should be `width: 100vw`, which you changed on the splash page. A higher resolution image would also be better. 
- [ ] The `restaurant-list` could be bigger with respect to show. If you `display: flex` the parent, `restaurant-list` can be `flex: 1` while `restaurant-detail` can be `flex: 3` or so.
- [ ] In your reset.css, have a default `font-family: sans-serif` to make the fonts consistent.
- [ ] Use a lighter gray for the background, such as `#f7f7f7`.

**Comment by anastassia-b** [comment]
Great, you've fixed the major styling issues. Please: 
- [ ] Add links to the footer. These can be to your personal pages, or "company links" to make it look legit which don't go anywhere (or to your linked in!).

Otherwise, this MVP is complete!
